---
# Installation
- name: Install Transmission
  apt: name=transmission-daemon state=present

# Configuration
- name: Make sure transmission is not running
  service: name=transmission-daemon state=stopped
  ignore_errors: true

- name: Add downloads folder
  file: path=/home/{{ transmission_user }}/{{ transmission_download_dir }} owner={{ transmission_user }} group={{ transmission_user }} state=directory mode=0777

- name: Add watch dir
  file: path=/home/{{ transmission_user }}/{{ transmission_watch_dir }} owner={{ transmission_user }} group={{ transmission_user }} state=directory
  when: transmission_watch_dir_enabled

- name: Add incomplete folder
  file: path=/home/{{ transmission_user }}/{{ transmission_incomplete_dir }} owner={{ transmission_user }} group={{ transmission_user }} state=directory mode=0777
  when: transmission_incomplete_dir_enabled

- name: Copy Transmission configuration
  template:
    src=settings.json
    dest=/etc/transmission-daemon/settings.json

# Service start
- name: Start transmission
  service: name=transmission-daemon state=started
  ignore_errors: true
